version: '3.6'
services:
    mosquitto:
      image: eclipse-mosquitto
      networks:
         - AI-Bot
         - traefik_default
      ports:
        - "1883:1883"
      configs:
        - source: mosquitto.conf
          target: /mosquitto/config/mosquitto.conf
      volumes:
        - mosquitto-data:/mosquitto/data
     
    kellyai:
      image: 192.168.1.222:5000/kellyai:latest
      networks:
         - AI-Bot
         - traefik_default
      deploy:
         labels:
           - "traefik.backend=kellyai"
           - "traefik.docker.network=traefik_default"
           - "traefik.frontend.rule=Host:kellyai.docker.xganon.com"
           - "traefik.port=54377"
           - "traefik.enable=true"        
      entrypoint: /usr/bin/mono-service -l\:Corrade.exe.lock --no-daemon Corrade.exe
     

    bot-ai:
       image: 192.168.1.222:5000/bot-ai:latest
       networks:
         - AI-Bot
         - traefik_default
       environment:
         MQTT_SERVER: mosquitto

networks:
   traefik_default:
     external: true
   AI-Bot:
     external: true
     
configs:
  mosquitto.conf:
     external: true

volumes:
  mosquitto-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.115,nolock,soft,rw
      device: ":/mnt/Homes/Docker/mosquitto"